# Generated by Django 4.1.4 on 2023-01-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_polls_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polls',
            options={'ordering': ['-pub_date']},
        ),
    ]
